---
# tasks file for buidserver
- name: Ensure the packages is present
  apt:  name={{item}} state=present
  with_items:
    - git
    - default-jdk
    - maven

- name: Ensure demo-project is downloaded
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: ./
    clone: yes

- name: Buid package
  shell: mvn package
  args:
    chdir: /boxfuse-sample-java-war-hello

- name: Ensure *.war is copied to webserver
  synchronize:
    mode: push
    src: /boxfuse-sample-java-war-hello
    dest: {{ dest_folder }}